/// Work Achievement Definitions
/// Corporate and work-focused achievements for employee motivation
///
/// These achievements are designed to motivate productivity, teamwork,
/// and professional growth in a corporate environment

import 'achievement_model.dart';

/// Work-specific achievement categories
enum WorkAchievementCategory {
  productivity,    // Productivity and efficiency
  teamwork,       // Team collaboration
  leadership,     // Leadership and mentoring
  quality,        // Quality of work
  deadlines,      // Meeting deadlines
  innovation,     // Innovation and initiative
  growth,         // Professional development
  consistency,    // Consistent performance
  communication,  // Communication skills
  collaboration,  // Cross-team collaboration
}

/// Work achievement definitions - 80+ achievements
class WorkAchievementDefinitions {
  static const List<AchievementModel> all = [
    // ===== PRODUCTIVITY ACHIEVEMENTS (10) =====
    AchievementModel(
      id: 'work_productivity_daily_5',
      name: 'Daily Driver',
      description: 'Complete 5 work tasks in one day',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.rare,
      icon: '💼',
      color: '#2196F3',
      condition: 'work_tasks_per_day',
      targetValue: 5,
      xpReward: 300,
      hint: 'Focus on completing multiple tasks daily',
    ),
    AchievementModel(
      id: 'work_productivity_weekly_25',
      name: 'Weekly Warrior',
      description: 'Complete 25 work tasks in one week',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.epic,
      icon: '📊',
      color: '#2196F3',
      condition: 'work_tasks_per_week',
      targetValue: 25,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'work_productivity_monthly_100',
      name: 'Monthly Master',
      description: 'Complete 100 work tasks in one month',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.legendary,
      icon: '📈',
      color: '#2196F3',
      condition: 'work_tasks_per_month',
      targetValue: 100,
      xpReward: 5000,
    ),
    AchievementModel(
      id: 'work_productivity_quick_finish',
      name: 'Quick Finisher',
      description: 'Complete 3 tasks before their due date',
      category: AchievementCategory.speed,
      rarity: AchievementRarity.rare,
      icon: '⚡',
      color: '#FFC107',
      condition: 'early_completions',
      targetValue: 3,
      xpReward: 400,
    ),
    AchievementModel(
      id: 'work_productivity_marathon',
      name: 'Task Marathon',
      description: 'Work on tasks for 8 hours straight',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🏃',
      color: '#4CAF50',
      condition: 'consecutive_hours_work',
      targetValue: 8,
      xpReward: 1500,
    ),
    AchievementModel(
      id: 'work_productivity_multi_task',
      name: 'Multi-tasker',
      description: 'Work on 5 different projects simultaneously',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🎯',
      color: '#9C27B0',
      condition: 'multiple_projects',
      targetValue: 5,
      xpReward: 600,
    ),
    AchievementModel(
      id: 'work_productivity_high_priority',
      name: 'Priority Crusher',
      description: 'Complete 20 high-priority tasks',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.epic,
      icon: '🔴',
      color: '#F44336',
      condition: 'high_priority_tasks',
      targetValue: 20,
      xpReward: 1200,
    ),
    AchievementModel(
      id: 'work_productivity_consistency',
      name: 'Consistent Performer',
      description: 'Complete at least 3 tasks every day for 7 days',
      category: AchievementCategory.streaks,
      rarity: AchievementRarity.legendary,
      icon: '📅',
      color: '#4CAF50',
      condition: 'daily_task_streak',
      targetValue: 7,
      xpReward: 2000,
    ),
    AchievementModel(
      id: 'work_productivity_rush_hour',
      name: 'Rush Hour Hero',
      description: 'Complete 10 tasks during peak hours (9-11 AM or 2-4 PM)',
      category: AchievementCategory.time,
      rarity: AchievementRarity.rare,
      icon: '⏰',
      color: '#FF9800',
      condition: 'peak_hour_tasks',
      targetValue: 10,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'work_productivity_efficiency',
      name: 'Efficiency Expert',
      description: 'Complete tasks with 90%+ estimated time accuracy',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '⏱️',
      color: '#009688',
      condition: 'time_accuracy',
      targetValue: 90,
      xpReward: 1500,
    ),

    // ===== DEADLINE ACHIEVEMENTS (10) =====
    AchievementModel(
      id: 'work_deadline_punctual_10',
      name: 'Punctual Professional',
      description: 'Submit 10 tasks on time',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '✅',
      color: '#4CAF50',
      condition: 'on_time_submissions',
      targetValue: 10,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'work_deadline_early_5',
      name: 'Early Bird Professional',
      description: 'Submit 5 tasks ahead of schedule',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🌅',
      color: '#FFC107',
      condition: 'early_submissions',
      targetValue: 5,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'work_deadline_perfect_month',
      name: 'Deadline Perfectionist',
      description: 'Submit all tasks on time for a full month',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '🎯',
      color: '#FFD700',
      condition: 'perfect_month',
      targetValue: 1,
      xpReward: 5000,
    ),
    AchievementModel(
      id: 'work_deadline_zero_overdue',
      name: 'Zero Overdue',
      description: 'Have no overdue tasks for 14 days',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '🛡️',
      color: '#4CAF50',
      condition: 'no_overdue_streak',
      targetValue: 14,
      xpReward: 2500,
    ),
    AchievementModel(
      id: 'work_deadline_crusher',
      name: 'Deadline Crusher',
      description: 'Complete 50 tasks before their deadline',
      category: AchievementCategory.special,
      rarity: AchievementRarity.mythic,
      icon: '💥',
      color: '#F44336',
      condition: 'early_completions_total',
      targetValue: 50,
      xpReward: 10000,
    ),
    AchievementModel(
      id: 'work_deadline_recovery',
      name: 'Deadline Recovery',
      description: 'Complete a task that was already overdue',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🔄',
      color: '#FF9800',
      condition: 'overdue_completion',
      targetValue: 1,
      xpReward: 400,
    ),
    AchievementModel(
      id: 'work_deadline_prevent',
      name: 'Deadline Preventer',
      description: 'Prevent 5 tasks from becoming overdue',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '⚠️',
      color: '#FFC107',
      condition: 'prevented_overdue',
      targetValue: 5,
      xpReward: 600,
    ),
    AchievementModel(
      id: 'work_deadline_urgent_handle',
      name: 'Urgent Handler',
      description: 'Complete 15 urgent tasks before deadline',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🚨',
      color: '#F44336',
      condition: 'urgent_on_time',
      targetValue: 15,
      xpReward: 1500,
    ),
    AchievementModel(
      id: 'work_deadline_planning',
      name: 'Deadline Planner',
      description: 'Set realistic deadlines for 20 tasks',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '📝',
      color: '#2196F3',
      condition: 'realistic_deadlines',
      targetValue: 20,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'work_deadline_streak',
      name: 'On-Time Streak',
      description: 'Submit tasks on time for 30 consecutive days',
      category: AchievementCategory.streaks,
      rarity: AchievementRarity.mythic,
      icon: '🔥',
      color: '#FFD700',
      condition: 'on_time_streak',
      targetValue: 30,
      xpReward: 10000,
    ),

    // ===== TEAMWORK ACHIEVEMENTS (10) =====
    AchievementModel(
      id: 'work_teamwork_assist',
      name: 'Team Player',
      description: 'Help a colleague complete their task',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🤝',
      color: '#4CAF50',
      condition: 'helped_colleague',
      targetValue: 1,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'work_teamwork_collab_10',
      name: 'Collaborator',
      description: 'Collaborate on 10 team tasks',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '👥',
      color: '#2196F3',
      condition: 'team_collaborations',
      targetValue: 10,
      xpReward: 800,
    ),
    AchievementModel(
      id: 'work_teamwork_share_knowledge',
      name: 'Knowledge Sharer',
      description: 'Share knowledge with 5 different colleagues',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '💡',
      color: '#FFC107',
      condition: 'knowledge_shared',
      targetValue: 5,
      xpReward: 600,
    ),
    AchievementModel(
      id: 'work_teamwork_mentor',
      name: 'Mentor',
      description: 'Mentor a new team member',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🎓',
      color: '#9C27B0',
      condition: 'mentored_newbie',
      targetValue: 1,
      xpReward: 1500,
    ),
    AchievementModel(
      id: 'work_teamwork_cross_team',
      name: 'Cross-Team Collaborator',
      description: 'Work with 3 different teams',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🔗',
      color: '#FF5722',
      condition: 'cross_team_work',
      targetValue: 3,
      xpReward: 1200,
    ),
    AchievementModel(
      id: 'work_teamwork_group_task',
      name: 'Group Task Master',
      description: 'Successfully complete 20 group tasks',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '👫',
      color: '#4CAF50',
      condition: 'group_tasks_completed',
      targetValue: 20,
      xpReward: 2500,
    ),
    AchievementModel(
      id: 'work_teamwork_feedback',
      name: 'Feedback Giver',
      description: 'Provide constructive feedback to 10 colleagues',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '💬',
      color: '#009688',
      condition: 'feedback_given',
      targetValue: 10,
      xpReward: 700,
    ),
    AchievementModel(
      id: 'work_teamwork_receive_feedback',
      name: 'Feedback Receiver',
      description: 'Receive positive feedback from 5 colleagues',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🎤',
      color: '#009688',
      condition: 'feedback_received',
      targetValue: 5,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'work_teamwork_resolution',
      name: 'Conflict Resolver',
      description: 'Help resolve a team conflict',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🕊️',
      color: '#3F51B5',
      condition: 'conflict_resolved',
      targetValue: 1,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'work_teamwork_celebration',
      name: 'Team Celebrator',
      description: 'Celebrate 5 team achievements',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🎉',
      color: '#FF9800',
      condition: 'team_celebrations',
      targetValue: 5,
      xpReward: 400,
    ),

    // ===== QUALITY ACHIEVEMENTS (10) =====
    AchievementModel(
      id: 'work_quality_rating_5',
      name: 'Quality Master',
      description: 'Receive 5-star rating from manager',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '⭐',
      color: '#FFD700',
      condition: 'five_star_rating',
      targetValue: 1,
      xpReward: 2000,
    ),
    AchievementModel(
      id: 'work_quality_ratings_10',
      name: 'Quality Champion',
      description: 'Receive high ratings for 10 tasks',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '🏆',
      color: '#FFD700',
      condition: 'high_ratings',
      targetValue: 10,
      xpReward: 5000,
    ),
    AchievementModel(
      id: 'work_quality_zero_revisions',
      name: 'First-Time Right',
      description: 'Complete 15 tasks without revisions',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '✅',
      color: '#4CAF50',
      condition: 'no_revisions',
      targetValue: 15,
      xpReward: 1500,
    ),
    AchievementModel(
      id: 'work_quality_excellence',
      name: 'Excellence Award',
      description: 'Exceed quality expectations on 20 tasks',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '👑',
      color: '#FFD700',
      condition: 'quality_excellence',
      targetValue: 20,
      xpReward: 4000,
    ),
    AchievementModel(
      id: 'work_quality_improvement',
      name: 'Quality Improver',
      description: 'Improve quality rating over 5 consecutive tasks',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '📈',
      color: '#4CAF50',
      condition: 'quality_improvement',
      targetValue: 5,
      xpReward: 800,
    ),
    AchievementModel(
      id: 'work_quality_attention',
      name: 'Detail Oriented',
      description: 'Catch 10 errors before submission',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🔍',
      color: '#2196F3',
      condition: 'errors_caught',
      targetValue: 10,
      xpReward: 600,
    ),
    AchievementModel(
      id: 'work_quality_consistency',
      name: 'Quality Consistency',
      description: 'Maintain high quality for 30 days',
      category: AchievementCategory.streaks,
      rarity: AchievementRarity.legendary,
      icon: '🎯',
      color: '#4CAF50',
      condition: 'quality_streak',
      targetValue: 30,
      xpReward: 6000,
    ),
    AchievementModel(
      id: 'work_quality_innovation',
      name: 'Quality Innovator',
      description: 'Suggest 3 quality improvement processes',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '💡',
      color: '#9C27B0',
      condition: 'quality_suggestions',
      targetValue: 3,
      xpReward: 1200,
    ),
    AchievementModel(
      id: 'work_quality_standards',
      name: 'Standards Keeper',
      description: 'Uphold quality standards for 50 tasks',
      category: AchievementCategory.special,
      rarity: AchievementRarity.mythic,
      icon: '📏',
      color: '#009688',
      condition: 'standards_upheld',
      targetValue: 50,
      xpReward: 10000,
    ),
    AchievementModel(
      id: 'work_quality_certification',
      name: 'Quality Certification',
      description: 'Achieve quality certification',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '🎓',
      color: '#3F51B5',
      condition: 'quality_cert',
      targetValue: 1,
      xpReward: 3000,
    ),

    // ===== LEADERSHIP ACHIEVEMENTS (10) =====
    AchievementModel(
      id: 'work_leadership_initiative',
      name: 'Take Initiative',
      description: 'Proactively start 5 improvement projects',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🚀',
      color: '#FF5722',
      condition: 'initiatives_taken',
      targetValue: 5,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'work_leadership_project_lead',
      name: 'Project Leader',
      description: 'Successfully lead 3 projects to completion',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '👔',
      color: '#2196F3',
      condition: 'projects_lead',
      targetValue: 3,
      xpReward: 2500,
    ),
    AchievementModel(
      id: 'work_leadership_mentor_3',
      name: 'Team Mentor',
      description: 'Mentor 3 new team members',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '🎓',
      color: '#9C27B0',
      condition: 'mentees_guided',
      targetValue: 3,
      xpReward: 3000,
    ),
    AchievementModel(
      id: 'work_leadership_decision',
      name: 'Decisive Leader',
      description: 'Make 10 important decisions quickly',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '⚡',
      color: '#FFC107',
      condition: 'decisions_made',
      targetValue: 10,
      xpReward: 800,
    ),
    AchievementModel(
      id: 'work_leadership_delegate',
      name: 'Effective Delegator',
      description: 'Successfully delegate 20 tasks',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '📋',
      color: '#009688',
      condition: 'tasks_delegated',
      targetValue: 20,
      xpReward: 1200,
    ),
    AchievementModel(
      id: 'work_leadership_vision',
      name: 'Visionary',
      description: 'Present a clear vision to the team 5 times',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🔮',
      color: '#9C27B0',
      condition: 'vision_presented',
      targetValue: 5,
      xpReward: 1500,
    ),
    AchievementModel(
      id: 'work_leadership_inspire',
      name: 'Team Inspirator',
      description: 'Inspire the team to achieve 5 goals',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '✨',
      color: '#FF9800',
      condition: 'team_inspired',
      targetValue: 5,
      xpReward: 1800,
    ),
    AchievementModel(
      id: 'work_leadership_change',
      name: 'Change Leader',
      description: 'Successfully lead 2 major changes',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '🔄',
      color: '#3F51B5',
      condition: 'changes_led',
      targetValue: 2,
      xpReward: 4000,
    ),
    AchievementModel(
      id: 'work_leadership_recognition',
      name: 'Leadership Recognition',
      description: 'Receive leadership award',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '🏅',
      color: '#FFD700',
      condition: 'leadership_award',
      targetValue: 1,
      xpReward: 5000,
    ),
    AchievementModel(
      id: 'work_leadership_succession',
      name: 'Succession Leader',
      description: 'Train 2 people to replace you in leadership',
      category: AchievementCategory.special,
      rarity: AchievementRarity.mythic,
      icon: '🌟',
      color: '#FFD700',
      condition: 'succession_trained',
      targetValue: 2,
      xpReward: 10000,
    ),

    // ===== INNOVATION ACHIEVEMENTS (10) =====
    AchievementModel(
      id: 'work_innovation_idea',
      name: 'Idea Generator',
      description: 'Suggest 5 process improvements',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '💡',
      color: '#FFC107',
      condition: 'improvement_ideas',
      targetValue: 5,
      xpReward: 800,
    ),
    AchievementModel(
      id: 'work_innovation_implement',
      name: 'Innovation Implementer',
      description: 'Implement 3 of your own ideas',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🔧',
      color: '#FF5722',
      condition: 'ideas_implemented',
      targetValue: 3,
      xpReward: 1500,
    ),
    AchievementModel(
      id: 'work_innovation_automation',
      name: 'Automation Expert',
      description: 'Automate 5 manual processes',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '🤖',
      color: '#009688',
      condition: 'processes_automated',
      targetValue: 5,
      xpReward: 3000,
    ),
    AchievementModel(
      id: 'work_innovation_creative',
      name: 'Creative Problem Solver',
      description: 'Solve 10 problems creatively',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🎨',
      color: '#9C27B0',
      condition: 'creative_solutions',
      targetValue: 10,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'work_innovation_efficiency',
      name: 'Efficiency Innovator',
      description: 'Improve efficiency by 20% in your area',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '⚡',
      color: '#FFC107',
      condition: 'efficiency_improved',
      targetValue: 20,
      xpReward: 2000,
    ),
    AchievementModel(
      id: 'work_innovation_patent',
      name: 'Inventor',
      description: 'File a patent or copyright',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '📜',
      color: '#3F51B5',
      condition: 'patent_filed',
      targetValue: 1,
      xpReward: 5000,
    ),
    AchievementModel(
      id: 'work_innovation_award',
      name: 'Innovation Award',
      description: 'Win company innovation award',
      category: AchievementCategory.special,
      rarity: AchievementRarity.mythic,
      icon: '🏆',
      color: '#FFD700',
      condition: 'innovation_award',
      targetValue: 1,
      xpReward: 10000,
    ),
    AchievementModel(
      id: 'work_innovation_research',
      name: 'Innovation Researcher',
      description: 'Research and present 3 new technologies',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🔬',
      color: '#2196F3',
      condition: 'tech_research',
      targetValue: 3,
      xpReward: 1200,
    ),
    AchievementModel(
      id: 'work_innovation_pilot',
      name: 'Pilot Program Leader',
      description: 'Successfully launch 2 pilot programs',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🚀',
      color: '#FF5722',
      condition: 'pilots_launched',
      targetValue: 2,
      xpReward: 2500,
    ),
    AchievementModel(
      id: 'work_innovation_adoption',
      name: 'Innovation Adopter',
      description: 'Adopt and master 5 new tools/technologies',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '📱',
      color: '#009688',
      condition: 'tools_adopted',
      targetValue: 5,
      xpReward: 1000,
    ),

    // ===== PROFESSIONAL GROWTH (10) =====
    AchievementModel(
      id: 'work_growth_skill_5',
      name: 'Skill Developer',
      description: 'Learn 5 new professional skills',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '📚',
      color: '#2196F3',
      condition: 'skills_learned',
      targetValue: 5,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'work_growth_certification',
      name: 'Certified Professional',
      description: 'Earn 3 professional certifications',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '🎓',
      color: '#9C27B0',
      condition: 'certifications_earned',
      targetValue: 3,
      xpReward: 5000,
    ),
    AchievementModel(
      id: 'work_growth_training',
      name: 'Training Enthusiast',
      description: 'Complete 10 professional training courses',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '📖',
      color: '#4CAF50',
      condition: 'trainings_completed',
      targetValue: 10,
      xpReward: 2000,
    ),
    AchievementModel(
      id: 'work_growth_conference',
      name: 'Conference Attendee',
      description: 'Attend 5 industry conferences',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🎤',
      color: '#FF9800',
      condition: 'conferences_attended',
      targetValue: 5,
      xpReward: 800,
    ),
    AchievementModel(
      id: 'work_growth_presentation',
      name: 'Conference Speaker',
      description: 'Present at 2 industry conferences',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '🎤',
      color: '#3F51B5',
      condition: 'presentations_given',
      targetValue: 2,
      xpReward: 3000,
    ),
    AchievementModel(
      id: 'work_growth_network',
      name: 'Networker',
      description: 'Network with 50 industry professionals',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🤝',
      color: '#009688',
      condition: 'professionals_networked',
      targetValue: 50,
      xpReward: 1200,
    ),
    AchievementModel(
      id: 'work_growth_promotion',
      name: 'Rising Star',
      description: 'Get promoted to next level',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '⬆️',
      color: '#FFD700',
      condition: 'promotion_earned',
      targetValue: 1,
      xpReward: 10000,
    ),
    AchievementModel(
      id: 'work_growth_knowledge_share',
      name: 'Knowledge Leader',
      description: 'Lead 5 knowledge-sharing sessions',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '📢',
      color: '#FF5722',
      condition: 'sessions_led',
      targetValue: 5,
      xpReward: 1500,
    ),
    AchievementModel(
      id: 'work_growth_self_improve',
      name: 'Self Improver',
      description: 'Identify and improve 10 personal weaknesses',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🔧',
      color: '#4CAF50',
      condition: 'weaknesses_improved',
      targetValue: 10,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'work_growth_expert',
      name: 'Subject Matter Expert',
      description: 'Become recognized expert in your field',
      category: AchievementCategory.special,
      rarity: AchievementRarity.mythic,
      icon: '👑',
      color: '#FFD700',
      condition: 'expert_recognized',
      targetValue: 1,
      xpReward: 15000,
    ),

    // ===== COMMUNICATION ACHIEVEMENTS (10) =====
    AchievementModel(
      id: 'work_communication_clear',
      name: 'Clear Communicator',
      description: 'Receive positive feedback on clarity 10 times',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '💬',
      color: '#2196F3',
      condition: 'clarity_feedback',
      targetValue: 10,
      xpReward: 800,
    ),
    AchievementModel(
      id: 'work_communication_response',
      name: 'Fast Responder',
      description: 'Respond to messages within 1 hour 95% of the time',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '⚡',
      color: '#FFC107',
      condition: 'fast_response_rate',
      targetValue: 95,
      xpReward: 1500,
    ),
    AchievementModel(
      id: 'work_communication_presentation',
      name: 'Presentation Pro',
      description: 'Deliver 10 successful presentations',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '📊',
      color: '#FF5722',
      condition: 'presentations_delivered',
      targetValue: 10,
      xpReward: 2000,
    ),
    AchievementModel(
      id: 'work_communication_write',
      name: 'Effective Writer',
      description: 'Write 20 clear and concise emails/reports',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '✍️',
      color: '#009688',
      condition: 'documents_written',
      targetValue: 20,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'work_communication_listen',
      name: 'Active Listener',
      description: 'Demonstrate active listening in 15 meetings',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '👂',
      color: '#9C27B0',
      condition: 'active_listening',
      targetValue: 15,
      xpReward: 600,
    ),
    AchievementModel(
      id: 'work_communication_cross_cultural',
      name: 'Cross-Cultural Communicator',
      description: 'Effectively communicate with 5 different cultures',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🌍',
      color: '#4CAF50',
      condition: 'cross_cultural_comm',
      targetValue: 5,
      xpReward: 1200,
    ),
    AchievementModel(
      id: 'work_communication_difficult',
      name: 'Difficult Conversation Master',
      description: 'Successfully navigate 5 difficult conversations',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🗣️',
      color: '#F44336',
      condition: 'difficult_conversations',
      targetValue: 5,
      xpReward: 1500,
    ),
    AchievementModel(
      id: 'work_communication_stakeholder',
      name: 'Stakeholder Manager',
      description: 'Manage communication for 10 different stakeholders',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '👥',
      color: '#3F51B5',
      condition: 'stakeholders_managed',
      targetValue: 10,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'work_communication_virtual',
      name: 'Virtual Communication Pro',
      description: 'Effectively communicate in 20 virtual meetings',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '💻',
      color: '#2196F3',
      condition: 'virtual_meetings',
      targetValue: 20,
      xpReward: 800,
    ),
    AchievementModel(
      id: 'work_communication_mediator',
      name: 'Mediator',
      description: 'Mediate 3 successful resolutions',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '⚖️',
      color: '#FF9800',
      condition: 'mediations_successful',
      targetValue: 3,
      xpReward: 2500,
    ),
  ];

  // ===== TEAM ACHIEVEMENTS (10) =====
  static const List<AchievementModel> teamAchievements = [
    AchievementModel(
      id: 'work_team_synchronized',
      name: 'Synchronized',
      description: 'Entire team completes daily tasks',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🎯',
      color: '#4CAF50',
      condition: 'team_daily_sync',
      targetValue: 1,
      xpReward: 2000,
    ),
    AchievementModel(
      id: 'work_team_zero_debt',
      name: 'Zero Debt',
      description: 'Team has no overdue tasks for a week',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '🛡️',
      color: '#4CAF50',
      condition: 'team_no_overdue',
      targetValue: 7,
      xpReward: 5000,
    ),
    AchievementModel(
      id: 'work_team_sprint_champions',
      name: 'Sprint Champions',
      description: 'Complete a project 1 week early',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '🏃',
      color: '#FFD700',
      condition: 'project_early_complete',
      targetValue: 1,
      xpReward: 10000,
    ),
    AchievementModel(
      id: 'work_team_collaboration',
      name: 'Team Spirit',
      description: '100% team participation in team tasks',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🤝',
      color: '#2196F3',
      condition: 'team_full_participation',
      targetValue: 100,
      xpReward: 3000,
    ),
    AchievementModel(
      id: 'work_team_department_pride',
      name: 'Department Pride',
      description: 'Best performing department of the month',
      category: AchievementCategory.special,
      rarity: AchievementRarity.mythic,
      icon: '👑',
      color: '#FFD700',
      condition: 'best_department_month',
      targetValue: 1,
      xpReward: 20000,
    ),
    AchievementModel(
      id: 'work_team_innovation',
      name: 'Innovation Team',
      description: 'Team proposes 5 process improvements',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '💡',
      color: '#9C27B0',
      condition: 'team_innovations',
      targetValue: 5,
      xpReward: 5000,
    ),
    AchievementModel(
      id: 'work_team_quality',
      name: 'Quality Team',
      description: 'Team maintains 95%+ quality rating for a month',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '⭐',
      color: '#FFD700',
      condition: 'team_quality_month',
      targetValue: 95,
      xpReward: 8000,
    ),
    AchievementModel(
      id: 'work_team_growth',
      name: 'Growing Team',
      description: 'All team members improve a skill',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '📈',
      color: '#4CAF50',
      condition: 'team_all_improve',
      targetValue: 1,
      xpReward: 3000,
    ),
    AchievementModel(
      id: 'work_team_support',
      name: 'Supportive Team',
      description: 'Team helps other teams 10 times',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🆘',
      color: '#FF5722',
      condition: 'team_helped_others',
      targetValue: 10,
      xpReward: 2000,
    ),
    AchievementModel(
      id: 'work_team_excellence',
      name: 'Team Excellence',
      description: 'Win team excellence award',
      category: AchievementCategory.special,
      rarity: AchievementRarity.mythic,
      icon: '🏆',
      color: '#FFD700',
      condition: 'team_excellence_award',
      targetValue: 1,
      xpReward: 25000,
    ),
  ];

  // ===== GETTERS =====

  /// Get all work achievements
  static List<AchievementModel> get allWork => all;

  /// Get all team achievements
  static List<AchievementModel> get allTeam => teamAchievements;

  /// Get all work and team achievements combined
  static List<AchievementModel> get allCombined => [...all, ...teamAchievements];

  /// Get achievements by work category
  static List<AchievementModel> getByCategory(WorkAchievementCategory category) {
    // Map work categories to base categories
    final baseCategory = _mapWorkCategoryToBase(category);
    return all.where((a) => a.category == baseCategory).toList();
  }

  /// Get achievements by rarity
  static List<AchievementModel> getByRarity(AchievementRarity rarity) {
    return allCombined.where((a) => a.rarity == rarity).toList();
  }

  /// Get achievement by ID
  static AchievementModel? getById(String id) {
    try {
      return allCombined.firstWhere((a) => a.id == id);
    } catch (e) {
      return null;
    }
  }

  /// Get total count of work achievements
  static int get workCount => all.length;

  /// Get total count of team achievements
  static int get teamCount => teamAchievements.length;

  /// Get total count of all work-related achievements
  static int get totalCount => allCombined.length;

  // ===== HELPER METHODS =====

  /// Map work achievement category to base AchievementCategory
  static AchievementCategory _mapWorkCategoryToBase(WorkAchievementCategory category) {
    switch (category) {
      case WorkAchievementCategory.productivity:
        return AchievementCategory.tasks;
      case WorkAchievementCategory.teamwork:
        return AchievementCategory.special;
      case WorkAchievementCategory.leadership:
        return AchievementCategory.special;
      case WorkAchievementCategory.quality:
        return AchievementCategory.special;
      case WorkAchievementCategory.deadlines:
        return AchievementCategory.special;
      case WorkAchievementCategory.innovation:
        return AchievementCategory.special;
      case WorkAchievementCategory.growth:
        return AchievementCategory.special;
      case WorkAchievementCategory.consistency:
        return AchievementCategory.streaks;
      case WorkAchievementCategory.communication:
        return AchievementCategory.special;
      case WorkAchievementCategory.collaboration:
        return AchievementCategory.special;
    }
  }
}
