import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Провайдер для управления языком приложения
final localeProvider = StateNotifierProvider<LocaleNotifier, Locale>((ref) {
  return LocaleNotifier();
});

class LocaleNotifier extends StateNotifier<Locale> {
  LocaleNotifier() : super(const Locale('en'));

  /// Переключает между русским и английским языками
  void toggleLanguage() {
    state = state.languageCode == 'en'
        ? const Locale('ru')
        : const Locale('en');
  }

  /// Устанавливает английский язык
  void setEnglish() {
    state = const Locale('en');
  }

  /// Устанавливает русский язык
  void setRussian() {
    state = const Locale('ru');
  }

  /// Устанавливает язык по коду ('en' | 'ru')
  void setLocale(String languageCode) {
    state = languageCode == 'ru' ? const Locale('ru') : const Locale('en');
  }

  /// Проверяет, является ли текущий язык русским
  bool get isRussian => state.languageCode == 'ru';

  /// Проверяет, является ли текущий язык английским
  bool get isEnglish => state.languageCode == 'en';
}

/// Сервис локализации с поддержкой английского и русского языков
class LocalizationService {
  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'appTitle': 'Modern CRM',
      'dashboard': 'Dashboard',
      'tasks': 'Tasks',
      'crm': 'CRM',
      'reports': 'Reports',
      'profile': 'Profile',
      'language': 'Language',
      'name': 'Name',
      'addTask': 'Add Task',
      'newClient': 'New Client',
      'aiAssistant': 'AI Assistant',
      'recentActivities': 'Recent Activities',
      'tasksCompleted': 'Tasks Completed',
      'activeDeals': 'Active Deals',
      'quickActions': 'Quick Actions',
      'noTasksFound': 'No tasks found',
      'noClientsFound': 'No clients found',
      'searchTasks': 'Search tasks...',
      'searchClients': 'Search clients...',
      'filterTasks': 'Filter Tasks',
      'filterClients': 'Filter Clients',
      'category': 'Category',
      'priority': 'Priority',
      'status': 'Status',
      'source': 'Source',
      'all': 'All',
      'low': 'Low',
      'medium': 'Medium',
      'high': 'High',
      'lead': 'Lead',
      'prospect': 'Prospect',
      'active': 'Active',
      'inactive': 'Inactive',
      'addNewTask': 'Add New Task',
      'taskTitle': 'Task Title',
      'taskTitleHint': 'Enter task title',
      'description': 'Description',
      'descriptionHint': 'Enter task description',
      'dueDateOptional': 'Due Date (Optional)',
      'selectDate': 'Select date',
      'createTask': 'Create Task',
      'taskUpdated': 'Task updated successfully!',
      'taskDeleted': 'Task deleted',
      'deleteTask': 'Delete Task',
      'deleteTaskConfirm': 'Are you sure you want to delete this task?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'clientDetails': 'Client Details',
      'addNewClient': 'Add New Client',
      'firstName': 'First Name',
      'firstNameHint': 'Enter first name',
      'lastName': 'Last Name',
      'lastNameHint': 'Enter last name',
      'email': 'Email',
      'emailHint': 'Enter email',
      'phoneOptional': 'Phone (Optional)',
      'phoneHint': 'Enter phone number',
      'companyOptional': 'Company (Optional)',
      'companyHint': 'Enter company name',
      'positionOptional': 'Position (Optional)',
      'positionHint': 'Enter position',
      'createClient': 'Create Client',
      'clientCreated': 'Client created!',
      'clientUpdated': 'Client updated successfully!',
      'clientDeleted': 'Client deleted',
      'deleteClient': 'Delete Client',
      'deleteClientConfirm': 'Are you sure you want to delete this client?',
      'totalClients': 'Total Clients',
      'leads': 'Leads',
      'inactiveClients': 'Inactive',
      'overview': 'Overview',
      'completed': 'Completed',
      'success': 'Success',
      'earned': 'Earned',
      'taskCompletion': 'Task Completion',
      'clientStatusDistribution': 'Client Status Distribution',
      'taskPriorityDistribution': 'Task Priority Distribution',
      'recentSummary': 'Recent Summary',
      'tasksCompletedToday': 'Tasks Completed Today',
      'newClientsThisWeek': 'New Clients This Week',
      'currentStreak': 'Current Streak',
      'days': 'days',
      'yourProgress': 'Your Progress',
      'level': 'Level',
      'xp': 'XP',
      'streak': 'streak',
      'editProfile': 'Edit Profile',
      'achievements': 'Achievements',
      'notifications': 'Notifications',
      'dataExport': 'Data Export',
      'version': 'Version',
      'appDescription':
          'A gamified task and client management app built with Flutter',
      'settings': 'Settings',
      'darkMode': 'Dark Mode',
      'pushNotifications': 'Push Notifications',
      'autoSync': 'Auto-sync',
      'soundEffects': 'Sound Effects',
      'goodMorning': 'Good morning! 👋',
      'welcomeBack': 'Welcome back to',
      'clearFilters': 'Clear Filters',
      'firstTask': 'First Task',
      'completeFirstTask': 'Complete your first task',
      'taskMaster': 'Task Master',
      'complete10Tasks': 'Complete 10 tasks',
      'streakKeeper': 'Streak Keeper',
      'maintain7DayStreak': 'Maintain a 7-day streak',
      'levelUp': 'Level Up',
      'reachLevel5': 'Reach level 5',
      'unlocked': 'Unlocked',
      'locked': 'Locked',
      'taskReminders': 'Task Reminders',
      'getNotifiedAboutUpcomingTasks': 'Get notified about upcoming tasks',
      'achievementAlerts': 'Achievement Alerts',
      'celebrateYourWins': 'Celebrate your wins',
      'dailySummary': 'Daily Summary',
      'dailyProductivityReport': 'Daily productivity report',
      'weeklyReports': 'Weekly Reports',
      'weeklyProgressSummary': 'Weekly progress summary',
      'aiAssistantTitle': 'AI Assistant',
      'askMeAnything': 'Ask me anything...',
      'quickSuggestions': 'Quick Suggestions',
      'howToBeMoreProductive': 'How to be more productive?',
      'taskManagementTips': 'Task management tips',
      'howToUseGamification': 'How to use gamification?',
      'clientRelationshipTips': 'Client relationship tips',
      'showMyStatistics': 'Show my statistics',
      'profileUpdated': 'Profile updated successfully!',
      'fullName': 'Full Name',
      'dataExportFeatureComingSoon': 'Data export feature coming soon!',
      'logout': 'Logout',
      'demoUser': 'Demo User',
      'welcome': 'Welcome!',
      'login': 'Login',
      'password': 'Password',
      'demoAccess': 'Demo access:',
      'enterEmail': 'Enter email',
      'invalidEmail': 'Invalid email',
      'enterPassword': 'Enter password',
      'passwordTooShort': 'Password too short',
      'loginSuccess': 'Login successful!',
      'loginError': 'Login error',
      'invalidCredentials': 'Invalid email or password',
      'useCredentials': 'Use: demo@crm.com / demo',
      'loading': 'Loading...',
      'save': 'Save',
      'back': 'Back',
      'continue': 'Continue',
      'yes': 'Yes',
      'no': 'No',
      'confirm': 'Confirm',
      'error': 'Error',
      'warning': 'Warning',
      'info': 'Info',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'tomorrow': 'Tomorrow',
      'week': 'Week',
      'month': 'Month',
      'year': 'Year',
      'january': 'January',
      'february': 'February',
      'march': 'March',
      'april': 'April',
      'may': 'May',
      'june': 'June',
      'july': 'July',
      'august': 'August',
      'september': 'September',
      'october': 'October',
      'november': 'November',
      'december': 'December',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
    },
    'ru': {
      'appTitle': 'Современная CRM',
      'dashboard': 'Главная',
      'tasks': 'Задачи',
      'crm': 'CRM',
      'reports': 'Отчёты',
      'profile': 'Профиль',
      'language': 'Язык',
      'name': 'Имя',
      'addTask': 'Добавить Задачу',
      'newClient': 'Новый Клиент',
      'aiAssistant': 'ИИ Ассистент',
      'recentActivities': 'Последние Активности',
      'tasksCompleted': 'Задач Выполнено',
      'activeDeals': 'Активные Сделки',
      'quickActions': 'Быстрые Действия',
      'noTasksFound': 'Задачи не найдены',
      'noClientsFound': 'Клиенты не найдены',
      'searchTasks': 'Поиск задач...',
      'searchClients': 'Поиск клиентов...',
      'filterTasks': 'Фильтр Задач',
      'filterClients': 'Фильтр Клиентов',
      'category': 'Категория',
      'priority': 'Приоритет',
      'status': 'Статус',
      'source': 'Источник',
      'all': 'Все',
      'low': 'Низкий',
      'medium': 'Средний',
      'high': 'Высокий',
      'lead': 'Лид',
      'prospect': 'Перспектива',
      'active': 'Активный',
      'inactive': 'Неактивный',
      'addNewTask': 'Добавить Новую Задачу',
      'taskTitle': 'Название Задачи',
      'taskTitleHint': 'Введите название задачи',
      'description': 'Описание',
      'descriptionHint': 'Введите описание задачи',
      'dueDateOptional': 'Срок Выполнения (Необязательно)',
      'selectDate': 'Выберите дату',
      'createTask': 'Создать Задачу',
      'taskUpdated': 'Задача обновлена успешно!',
      'taskDeleted': 'Задача удалена',
      'deleteTask': 'Удалить Задачу',
      'deleteTaskConfirm': 'Вы уверены, что хотите удалить эту задачу?',
      'cancel': 'Отмена',
      'delete': 'Удалить',
      'edit': 'Редактировать',
      'clientDetails': 'Детали Клиента',
      'addNewClient': 'Добавить Нового Клиента',
      'firstName': 'Имя',
      'firstNameHint': 'Введите имя',
      'lastName': 'Фамилия',
      'lastNameHint': 'Введите фамилию',
      'email': 'Email',
      'emailHint': 'Введите email',
      'phoneOptional': 'Телефон (Необязательно)',
      'phoneHint': 'Введите номер телефона',
      'companyOptional': 'Компания (Необязательно)',
      'companyHint': 'Введите название компании',
      'positionOptional': 'Должность (Необязательно)',
      'positionHint': 'Введите должность',
      'createClient': 'Создать Клиента',
      'clientCreated': 'Клиент создан!',
      'clientUpdated': 'Клиент обновлён успешно!',
      'clientDeleted': 'Клиент удалён',
      'deleteClient': 'Удалить Клиента',
      'deleteClientConfirm': 'Вы уверены, что хотите удалить этого клиента?',
      'totalClients': 'Всего Клиентов',
      'leads': 'Лиды',
      'inactiveClients': 'Неактивные',
      'overview': 'Обзор',
      'completed': 'Выполнено',
      'success': 'Успех',
      'earned': 'Заработано',
      'taskCompletion': 'Выполнение Задач',
      'clientStatusDistribution': 'Распределение Статусов Клиентов',
      'taskPriorityDistribution': 'Распределение Приоритетов Задач',
      'recentSummary': 'Сводка',
      'tasksCompletedToday': 'Задач Выполнено Сегодня',
      'newClientsThisWeek': 'Новых Клиентов на Этой Неделе',
      'currentStreak': 'Текущая Серия',
      'days': 'дней',
      'yourProgress': 'Ваш Прогресс',
      'level': 'Уровень',
      'xp': 'Опыт',
      'streak': 'серия',
      'editProfile': 'Редактировать Профиль',
      'achievements': 'Достижения',
      'notifications': 'Уведомления',
      'dataExport': 'Экспорт Данных',
      'version': 'Версия',
      'appDescription':
          'Геймифицированное приложение для управления задачами и клиентами, созданное на Flutter',
      'settings': 'Настройки',
      'darkMode': 'Тёмная Тема',
      'pushNotifications': 'Push-уведомления',
      'autoSync': 'Автосинхронизация',
      'soundEffects': 'Звуковые Эффекты',
      'goodMorning': 'Доброе утро! 👋',
      'welcomeBack': 'С возвращением в',
      'clearFilters': 'Очистить Фильтры',
      'firstTask': 'Первая Задача',
      'completeFirstTask': 'Выполните свою первую задачу',
      'taskMaster': 'Мастер Задач',
      'complete10Tasks': 'Выполните 10 задач',
      'streakKeeper': 'Хранитель Серии',
      'maintain7DayStreak': 'Поддерживайте серию 7 дней',
      'levelUp': 'Повышение Уровня',
      'reachLevel5': 'Достигните 5 уровня',
      'unlocked': 'Разблокировано',
      'locked': 'Заблокировано',
      'taskReminders': 'Напоминания о Задачах',
      'getNotifiedAboutUpcomingTasks':
          'Получайте уведомления о предстоящих задачах',
      'achievementAlerts': 'Уведомления о Достижениях',
      'celebrateYourWins': 'Празднуйте свои победы',
      'dailySummary': 'Ежедневная Сводка',
      'dailyProductivityReport': 'Ежедневный отчёт о продуктивности',
      'weeklyReports': 'Еженедельные Отчёты',
      'weeklyProgressSummary': 'Еженедельная сводка прогресса',
      'aiAssistantTitle': 'ИИ Ассистент',
      'askMeAnything': 'Спросите меня о чём угодно...',
      'quickSuggestions': 'Быстрые Предложения',
      'howToBeMoreProductive': 'Как быть более продуктивным?',
      'taskManagementTips': 'Советы по управлению задачами',
      'howToUseGamification': 'Как использовать геймификацию?',
      'clientRelationshipTips': 'Советы по работе с клиентами',
      'showMyStatistics': 'Показать мою статистику',
      'profileUpdated': 'Профиль обновлён успешно!',
      'fullName': 'Полное Имя',
      'dataExportFeatureComingSoon': 'Функция экспорта данных скоро появится!',
      'logout': 'Выйти',
      'demoUser': 'Демо Пользователь',
      'welcome': 'Добро пожаловать!',
      'login': 'Войти',
      'password': 'Пароль',
      'demoAccess': 'Демо доступ:',
      'enterEmail': 'Введите email',
      'invalidEmail': 'Некорректный email',
      'enterPassword': 'Введите пароль',
      'passwordTooShort': 'Пароль слишком короткий',
      'loginSuccess': 'Успешный вход!',
      'loginError': 'Ошибка входа',
      'invalidCredentials': 'Неверный email или пароль',
      'useCredentials': 'Используйте: demo@crm.com / demo',
      'loading': 'Загрузка...',
      'save': 'Сохранить',
      'back': 'Назад',
      'continue': 'Продолжить',
      'yes': 'Да',
      'no': 'Нет',
      'confirm': 'Подтвердить',
      'error': 'Ошибка',
      'warning': 'Предупреждение',
      'info': 'Информация',
      'today': 'Сегодня',
      'yesterday': 'Вчера',
      'tomorrow': 'Завтра',
      'week': 'Неделя',
      'month': 'Месяц',
      'year': 'Год',
      'january': 'Январь',
      'february': 'Февраль',
      'march': 'Март',
      'april': 'Апрель',
      'may': 'Май',
      'june': 'Июнь',
      'july': 'Июль',
      'august': 'Август',
      'september': 'Сентябрь',
      'october': 'Октябрь',
      'november': 'Ноябрь',
      'december': 'Декабрь',
      'monday': 'Понедельник',
      'tuesday': 'Вторник',
      'wednesday': 'Среда',
      'thursday': 'Четверг',
      'friday': 'Пятница',
      'saturday': 'Суббота',
      'sunday': 'Воскресенье',
    },
  };

  /// Получает перевод для текущего языка
  static String translate(Locale locale, String key) {
    final lang = locale.languageCode;
    final translations = _translations[lang] ?? _translations['en']!;
    return translations[key] ?? key;
  }

  /// Расширение для Locale для удобного доступа к переводам
  static String of(BuildContext context, String key) {
    final locale = Localizations.localeOf(context);
    return translate(locale, key);
  }
}

/// Хук для использования локализации в виджетах
extension LocalizationExtension on BuildContext {
  String t(String key) {
    return LocalizationExtension._localeOf(this, key);
  }

  static String _localeOf(BuildContext context, String key) {
    final locale = Localizations.localeOf(context);
    return LocalizationService.translate(locale, key);
  }
}
