/// Achievement Model
/// Educational Project - Gamified Task Management App
///
/// Represents an achievement badge and its properties

import 'package:freezed_annotation/freezed_annotation.dart';

part 'achievement_model.freezed.dart';
part 'achievement_model.g.dart';

/// Achievement categories
enum AchievementCategory {
  streaks,
  completions,
  speed,
  special,
  levels,
  xp,
  tasks,
  time,
}

/// Achievement rarity
enum AchievementRarity {
  common,
  rare,
  epic,
  legendary,
  mythic,
}

@freezed
class AchievementModel with _$AchievementModel {
  const AchievementModel._(); // Added for getters

  const factory AchievementModel({
    required String id,
    required String name,
    required String description,
    required AchievementCategory category,
    required AchievementRarity rarity,
    required String icon,
    required String color,
    required String condition,
    required int targetValue,
    required int xpReward,
    String? hint,
    @Default(false) bool isHidden,
  }) = _AchievementModel;

  factory AchievementModel.fromJson(Map<String, dynamic> json) =>
      _$AchievementModelFromJson(json);

  /// Get rarity display name
  String get rarityDisplayName {
    switch (rarity) {
      case AchievementRarity.common:
        return 'Common';
      case AchievementRarity.rare:
        return 'Rare';
      case AchievementRarity.epic:
        return 'Epic';
      case AchievementRarity.legendary:
        return 'Legendary';
      case AchievementRarity.mythic:
        return 'Mythic';
    }
  }

  /// Get category display name
  String get categoryDisplayName {
    switch (category) {
      case AchievementCategory.streaks:
        return 'Streaks';
      case AchievementCategory.completions:
        return 'Completions';
      case AchievementCategory.speed:
        return 'Speed';
      case AchievementCategory.special:
        return 'Special';
      case AchievementCategory.levels:
        return 'Levels';
      case AchievementCategory.xp:
        return 'XP';
      case AchievementCategory.tasks:
        return 'Tasks';
      case AchievementCategory.time:
        return 'Time';
    }
  }

  /// Get rarity color
  String get rarityColor {
    switch (rarity) {
      case AchievementRarity.common:
        return '#9E9E9E';
      case AchievementRarity.rare:
        return '#2196F3';
      case AchievementRarity.epic:
        return '#9C27B0';
      case AchievementRarity.legendary:
        return '#FF9800';
      case AchievementRarity.mythic:
        return '#FFD700';
    }
  }
}

/// User Achievement Progress
@freezed
class UserAchievement with _$UserAchievement {
  const factory UserAchievement({
    required String id,
    required String achievementId,
    required String userId,
    required DateTime unlockedAt,
    required int progress,
    required bool isUnlocked,
  }) = _UserAchievement;

  factory UserAchievement.fromJson(Map<String, dynamic> json) =>
      _$UserAchievementFromJson(json);
}

/// Achievement Definition - 100+ predefined achievements
class AchievementDefinitions {
  static const List<AchievementModel> all = [
    // STREAK ACHIEVEMENTS (10)
    AchievementModel(
      id: 'streak_1',
      name: 'Getting Started',
      description: 'Complete tasks for 1 day in a row',
      category: AchievementCategory.streaks,
      rarity: AchievementRarity.common,
      icon: '🔥',
      color: '#FF5722',
      condition: 'streak_days',
      targetValue: 1,
      xpReward: 50,
      hint: 'Complete any task',
    ),
    AchievementModel(
      id: 'streak_3',
      name: 'Building Habits',
      description: 'Complete tasks for 3 days in a row',
      category: AchievementCategory.streaks,
      rarity: AchievementRarity.common,
      icon: '🔥',
      color: '#FF5722',
      condition: 'streak_days',
      targetValue: 3,
      xpReward: 100,
      hint: 'Complete tasks for 3 consecutive days',
    ),
    AchievementModel(
      id: 'streak_7',
      name: 'Week Warrior',
      description: 'Complete tasks for 7 days in a row',
      category: AchievementCategory.streaks,
      rarity: AchievementRarity.rare,
      icon: '🔥',
      color: '#FF5722',
      condition: 'streak_days',
      targetValue: 7,
      xpReward: 250,
      hint: 'One full week of consistency',
    ),
    AchievementModel(
      id: 'streak_14',
      name: 'Dedication',
      description: 'Complete tasks for 14 days in a row',
      category: AchievementCategory.streaks,
      rarity: AchievementRarity.rare,
      icon: '🔥',
      color: '#FF5722',
      condition: 'streak_days',
      targetValue: 14,
      xpReward: 500,
      hint: 'Half a month of dedication',
    ),
    AchievementModel(
      id: 'streak_30',
      name: 'Month Master',
      description: 'Complete tasks for 30 days in a row',
      category: AchievementCategory.streaks,
      rarity: AchievementRarity.epic,
      icon: '🔥',
      color: '#FF5722',
      condition: 'streak_days',
      targetValue: 30,
      xpReward: 1000,
      hint: 'Complete a full month',
    ),
    AchievementModel(
      id: 'streak_60',
      name: 'Consistency King',
      description: 'Complete tasks for 60 days in a row',
      category: AchievementCategory.streaks,
      rarity: AchievementRarity.legendary,
      icon: '🔥',
      color: '#FF5722',
      condition: 'streak_days',
      targetValue: 60,
      xpReward: 2500,
      hint: 'Two months of unwavering commitment',
    ),
    AchievementModel(
      id: 'streak_100',
      name: 'Century Streak',
      description: 'Complete tasks for 100 days in a row',
      category: AchievementCategory.streaks,
      rarity: AchievementRarity.mythic,
      icon: '🔥',
      color: '#FF5722',
      condition: 'streak_days',
      targetValue: 100,
      xpReward: 5000,
      hint: 'The ultimate streak achievement',
    ),
    AchievementModel(
      id: 'streak_200',
      name: 'Legendary Fire',
      description: 'Complete tasks for 200 days in a row',
      category: AchievementCategory.streaks,
      rarity: AchievementRarity.mythic,
      icon: '🔥',
      color: '#FF5722',
      condition: 'streak_days',
      targetValue: 200,
      xpReward: 10000,
      hint: 'Over 6 months of perfection',
    ),
    AchievementModel(
      id: 'streak_365',
      name: 'Year of Fire',
      description: 'Complete tasks for 365 days in a row',
      category: AchievementCategory.streaks,
      rarity: AchievementRarity.mythic,
      icon: '🔥',
      color: '#FF5722',
      condition: 'streak_days',
      targetValue: 365,
      xpReward: 25000,
      hint: 'A full year of dedication',
    ),
    AchievementModel(
      id: 'streak_500',
      name: 'Eternal Flame',
      description: 'Complete tasks for 500 days in a row',
      category: AchievementCategory.streaks,
      rarity: AchievementRarity.mythic,
      icon: '🔥',
      color: '#FF5722',
      condition: 'streak_days',
      targetValue: 500,
      xpReward: 50000,
      hint: 'Over a year and a half',
    ),

    // TASK COMPLETION ACHIEVEMENTS (10)
    AchievementModel(
      id: 'tasks_1',
      name: 'First Steps',
      description: 'Complete your first task',
      category: AchievementCategory.completions,
      rarity: AchievementRarity.common,
      icon: '✅',
      color: '#4CAF50',
      condition: 'tasks_completed',
      targetValue: 1,
      xpReward: 25,
    ),
    AchievementModel(
      id: 'tasks_10',
      name: 'Task Apprentice',
      description: 'Complete 10 tasks',
      category: AchievementCategory.completions,
      rarity: AchievementRarity.common,
      icon: '✅',
      color: '#4CAF50',
      condition: 'tasks_completed',
      targetValue: 10,
      xpReward: 100,
    ),
    AchievementModel(
      id: 'tasks_25',
      name: 'Task Achiever',
      description: 'Complete 25 tasks',
      category: AchievementCategory.completions,
      rarity: AchievementRarity.rare,
      icon: '✅',
      color: '#4CAF50',
      condition: 'tasks_completed',
      targetValue: 25,
      xpReward: 250,
    ),
    AchievementModel(
      id: 'tasks_50',
      name: 'Task Master',
      description: 'Complete 50 tasks',
      category: AchievementCategory.completions,
      rarity: AchievementRarity.rare,
      icon: '✅',
      color: '#4CAF50',
      condition: 'tasks_completed',
      targetValue: 50,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'tasks_100',
      name: 'Century Scorer',
      description: 'Complete 100 tasks',
      category: AchievementCategory.completions,
      rarity: AchievementRarity.epic,
      icon: '✅',
      color: '#4CAF50',
      condition: 'tasks_completed',
      targetValue: 100,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'tasks_250',
      name: 'Quarter Master',
      description: 'Complete 250 tasks',
      category: AchievementCategory.completions,
      rarity: AchievementRarity.epic,
      icon: '✅',
      color: '#4CAF50',
      condition: 'tasks_completed',
      targetValue: 250,
      xpReward: 2500,
    ),
    AchievementModel(
      id: 'tasks_500',
      name: 'Halfway Hero',
      description: 'Complete 500 tasks',
      category: AchievementCategory.completions,
      rarity: AchievementRarity.legendary,
      icon: '✅',
      color: '#4CAF50',
      condition: 'tasks_completed',
      targetValue: 500,
      xpReward: 5000,
    ),
    AchievementModel(
      id: 'tasks_1000',
      name: 'Millennium Master',
      description: 'Complete 1000 tasks',
      category: AchievementCategory.completions,
      rarity: AchievementRarity.mythic,
      icon: '✅',
      color: '#4CAF50',
      condition: 'tasks_completed',
      targetValue: 1000,
      xpReward: 10000,
    ),
    AchievementModel(
      id: 'tasks_2500',
      name: 'Task Titan',
      description: 'Complete 2500 tasks',
      category: AchievementCategory.completions,
      rarity: AchievementRarity.mythic,
      icon: '✅',
      color: '#4CAF50',
      condition: 'tasks_completed',
      targetValue: 2500,
      xpReward: 25000,
    ),
    AchievementModel(
      id: 'tasks_5000',
      name: 'Task Legend',
      description: 'Complete 5000 tasks',
      category: AchievementCategory.completions,
      rarity: AchievementRarity.mythic,
      icon: '✅',
      color: '#4CAF50',
      condition: 'tasks_completed',
      targetValue: 5000,
      xpReward: 50000,
    ),

    // SPEED ACHIEVEMENTS (10)
    AchievementModel(
      id: 'speed_1hour',
      name: 'Speed Demon',
      description: 'Complete a task within 1 hour of creating it',
      category: AchievementCategory.speed,
      rarity: AchievementRarity.rare,
      icon: '⚡',
      color: '#FFC107',
      condition: 'quick_completion',
      targetValue: 1,
      xpReward: 100,
      hint: 'Create and complete a task quickly',
    ),
    AchievementModel(
      id: 'speed_3tasks',
      name: 'Rapid Fire',
      description: 'Complete 3 tasks in one day',
      category: AchievementCategory.speed,
      rarity: AchievementRarity.rare,
      icon: '⚡',
      color: '#FFC107',
      condition: 'tasks_per_day',
      targetValue: 3,
      xpReward: 200,
    ),
    AchievementModel(
      id: 'speed_5tasks',
      name: 'Productivity Machine',
      description: 'Complete 5 tasks in one day',
      category: AchievementCategory.speed,
      rarity: AchievementRarity.epic,
      icon: '⚡',
      color: '#FFC107',
      condition: 'tasks_per_day',
      targetValue: 5,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'speed_10tasks',
      name: 'Task Tornado',
      description: 'Complete 10 tasks in one day',
      category: AchievementCategory.speed,
      rarity: AchievementRarity.legendary,
      icon: '⚡',
      color: '#FFC107',
      condition: 'tasks_per_day',
      targetValue: 10,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'speed_20tasks',
      name: 'Unstoppable Force',
      description: 'Complete 20 tasks in one day',
      category: AchievementCategory.speed,
      rarity: AchievementRarity.mythic,
      icon: '⚡',
      color: '#FFC107',
      condition: 'tasks_per_day',
      targetValue: 20,
      xpReward: 2500,
    ),
    AchievementModel(
      id: 'speed_5in_hour',
      name: 'Flash Fighter',
      description: 'Complete 5 tasks within an hour',
      category: AchievementCategory.speed,
      rarity: AchievementRarity.legendary,
      icon: '⚡',
      color: '#FFC107',
      condition: 'tasks_per_hour',
      targetValue: 5,
      xpReward: 1500,
    ),
    AchievementModel(
      id: 'speed_10in_hour',
      name: 'Lightning Speed',
      description: 'Complete 10 tasks within an hour',
      category: AchievementCategory.speed,
      rarity: AchievementRarity.mythic,
      icon: '⚡',
      color: '#FFC107',
      condition: 'tasks_per_hour',
      targetValue: 10,
      xpReward: 3000,
    ),
    AchievementModel(
      id: 'speed_combo',
      name: 'Combo Master',
      description: 'Complete 5 tasks without a break',
      category: AchievementCategory.speed,
      rarity: AchievementRarity.epic,
      icon: '⚡',
      color: '#FFC107',
      condition: 'no_break',
      targetValue: 5,
      xpReward: 800,
    ),
    AchievementModel(
      id: 'speed_marathon',
      name: 'Speed Marathon',
      description: 'Complete 50 tasks in a week',
      category: AchievementCategory.speed,
      rarity: AchievementRarity.legendary,
      icon: '⚡',
      color: '#FFC107',
      condition: 'tasks_per_week',
      targetValue: 50,
      xpReward: 2000,
    ),
    AchievementModel(
      id: 'speed_burst',
      name: 'Speed Burst',
      description: 'Complete tasks for 2 hours straight',
      category: AchievementCategory.speed,
      rarity: AchievementRarity.rare,
      icon: '⚡',
      color: '#FFC107',
      condition: 'consecutive_hours',
      targetValue: 2,
      xpReward: 300,
    ),

    // LEVEL ACHIEVEMENTS (10)
    AchievementModel(
      id: 'level_1',
      name: 'Level One',
      description: 'Reach Level 1',
      category: AchievementCategory.levels,
      rarity: AchievementRarity.common,
      icon: '⭐',
      color: '#9C27B0',
      condition: 'current_level',
      targetValue: 1,
      xpReward: 0,
    ),
    AchievementModel(
      id: 'level_5',
      name: 'Rising Star',
      description: 'Reach Level 5',
      category: AchievementCategory.levels,
      rarity: AchievementRarity.rare,
      icon: '⭐',
      color: '#9C27B0',
      condition: 'current_level',
      targetValue: 5,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'level_10',
      name: 'Level Master',
      description: 'Reach Level 10',
      category: AchievementCategory.levels,
      rarity: AchievementRarity.epic,
      icon: '⭐',
      color: '#9C27B0',
      condition: 'current_level',
      targetValue: 10,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'level_25',
      name: 'Elite Achiever',
      description: 'Reach Level 25',
      category: AchievementCategory.levels,
      rarity: AchievementRarity.epic,
      icon: '⭐',
      color: '#9C27B0',
      condition: 'current_level',
      targetValue: 25,
      xpReward: 2500,
    ),
    AchievementModel(
      id: 'level_50',
      name: 'Master of Levels',
      description: 'Reach Level 50',
      category: AchievementCategory.levels,
      rarity: AchievementRarity.legendary,
      icon: '⭐',
      color: '#9C27B0',
      condition: 'current_level',
      targetValue: 50,
      xpReward: 5000,
    ),
    AchievementModel(
      id: 'level_100',
      name: 'Century Level',
      description: 'Reach Level 100',
      category: AchievementCategory.levels,
      rarity: AchievementRarity.mythic,
      icon: '⭐',
      color: '#9C27B0',
      condition: 'current_level',
      targetValue: 100,
      xpReward: 10000,
    ),
    AchievementModel(
      id: 'level_5_quick',
      name: 'Quick Rise',
      description: 'Reach Level 5 within 30 days',
      category: AchievementCategory.levels,
      rarity: AchievementRarity.rare,
      icon: '⭐',
      color: '#9C27B0',
      condition: 'level_in_days',
      targetValue: 5,
      xpReward: 800,
      hint: 'Reach level 5 in your first month',
    ),
    AchievementModel(
      id: 'level_10_quick',
      name: 'Rapid Progression',
      description: 'Reach Level 10 within 60 days',
      category: AchievementCategory.levels,
      rarity: AchievementRarity.epic,
      icon: '⭐',
      color: '#9C27B0',
      condition: 'level_in_days',
      targetValue: 10,
      xpReward: 1500,
      hint: 'Reach level 10 in 2 months',
    ),
    AchievementModel(
      id: 'level_double',
      name: 'Level Doubler',
      description: 'Level up twice in one day',
      category: AchievementCategory.levels,
      rarity: AchievementRarity.legendary,
      icon: '⭐',
      color: '#9C27B0',
      condition: 'levels_per_day',
      targetValue: 2,
      xpReward: 2000,
    ),
    AchievementModel(
      id: 'level_triple',
      name: 'Triple Threat',
      description: 'Level up three times in one day',
      category: AchievementCategory.levels,
      rarity: AchievementRarity.mythic,
      icon: '⭐',
      color: '#9C27B0',
      condition: 'levels_per_day',
      targetValue: 3,
      xpReward: 5000,
    ),

    // XP ACHIEVEMENTS (10)
    AchievementModel(
      id: 'xp_100',
      name: 'XP Explorer',
      description: 'Earn 100 total XP',
      category: AchievementCategory.xp,
      rarity: AchievementRarity.common,
      icon: '💰',
      color: '#FFD700',
      condition: 'total_xp',
      targetValue: 100,
      xpReward: 50,
    ),
    AchievementModel(
      id: 'xp_1000',
      name: 'XP Collector',
      description: 'Earn 1000 total XP',
      category: AchievementCategory.xp,
      rarity: AchievementRarity.rare,
      icon: '💰',
      color: '#FFD700',
      condition: 'total_xp',
      targetValue: 1000,
      xpReward: 200,
    ),
    AchievementModel(
      id: 'xp_5000',
      name: 'XP Master',
      description: 'Earn 5000 total XP',
      category: AchievementCategory.xp,
      rarity: AchievementRarity.epic,
      icon: '💰',
      color: '#FFD700',
      condition: 'total_xp',
      targetValue: 5000,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'xp_10000',
      name: 'XP Champion',
      description: 'Earn 10000 total XP',
      category: AchievementCategory.xp,
      rarity: AchievementRarity.legendary,
      icon: '💰',
      color: '#FFD700',
      condition: 'total_xp',
      targetValue: 10000,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'xp_50000',
      name: 'XP Legend',
      description: 'Earn 50000 total XP',
      category: AchievementCategory.xp,
      rarity: AchievementRarity.mythic,
      icon: '💰',
      color: '#FFD700',
      condition: 'total_xp',
      targetValue: 50000,
      xpReward: 2500,
    ),
    AchievementModel(
      id: 'xp_100000',
      name: 'XP Myth',
      description: 'Earn 100000 total XP',
      category: AchievementCategory.xp,
      rarity: AchievementRarity.mythic,
      icon: '💰',
      color: '#FFD700',
      condition: 'total_xp',
      targetValue: 100000,
      xpReward: 5000,
    ),
    AchievementModel(
      id: 'xp_1000_day',
      name: 'XP Powerhouse',
      description: 'Earn 1000 XP in one day',
      category: AchievementCategory.xp,
      rarity: AchievementRarity.epic,
      icon: '💰',
      color: '#FFD700',
      condition: 'xp_per_day',
      targetValue: 1000,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'xp_5000_week',
      name: 'Weekly XP',
      description: 'Earn 5000 XP in one week',
      category: AchievementCategory.xp,
      rarity: AchievementRarity.legendary,
      icon: '💰',
      color: '#FFD700',
      condition: 'xp_per_week',
      targetValue: 5000,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'xp_25000_month',
      name: 'Monthly XP',
      description: 'Earn 25000 XP in one month',
      category: AchievementCategory.xp,
      rarity: AchievementRarity.legendary,
      icon: '💰',
      color: '#FFD700',
      condition: 'xp_per_month',
      targetValue: 25000,
      xpReward: 2500,
    ),
    AchievementModel(
      id: 'xp_bonus',
      name: 'Bonus Hunter',
      description: 'Earn 500 XP from bonuses',
      category: AchievementCategory.xp,
      rarity: AchievementRarity.rare,
      icon: '💰',
      color: '#FFD700',
      condition: 'bonus_xp',
      targetValue: 500,
      xpReward: 200,
      hint: 'Complete tasks early for bonuses',
    ),

    // PRIORITY ACHIEVEMENTS (10)
    AchievementModel(
      id: 'priority_urgent_10',
      name: 'Crisis Manager',
      description: 'Complete 10 urgent tasks',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.rare,
      icon: '🚨',
      color: '#F44336',
      condition: 'urgent_tasks',
      targetValue: 10,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'priority_urgent_50',
      name: 'Emergency Expert',
      description: 'Complete 50 urgent tasks',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.legendary,
      icon: '🚨',
      color: '#F44336',
      condition: 'urgent_tasks',
      targetValue: 50,
      xpReward: 2500,
    ),
    AchievementModel(
      id: 'priority_high_25',
      name: 'Priority Pro',
      description: 'Complete 25 high priority tasks',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.rare,
      icon: '⬆️',
      color: '#FF9800',
      condition: 'high_tasks',
      targetValue: 25,
      xpReward: 250,
    ),
    AchievementModel(
      id: 'priority_high_100',
      name: 'High Achiever',
      description: 'Complete 100 high priority tasks',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.epic,
      icon: '⬆️',
      color: '#FF9800',
      condition: 'high_tasks',
      targetValue: 100,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'priority_medium_50',
      name: 'Steady Performer',
      description: 'Complete 50 medium priority tasks',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.common,
      icon: '➡️',
      color: '#2196F3',
      condition: 'medium_tasks',
      targetValue: 50,
      xpReward: 100,
    ),
    AchievementModel(
      id: 'priority_low_100',
      name: 'Small Wins',
      description: 'Complete 100 low priority tasks',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.common,
      icon: '⬇️',
      color: '#9E9E9E',
      condition: 'low_tasks',
      targetValue: 100,
      xpReward: 50,
    ),
    AchievementModel(
      id: 'priority_variety',
      name: 'Balanced Approach',
      description: 'Complete tasks of all priorities',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '⚖️',
      color: '#4CAF50',
      condition: 'all_priorities',
      targetValue: 4,
      xpReward: 500,
      hint: 'Complete at least one task of each priority',
    ),
    AchievementModel(
      id: 'priority_urgent_combo',
      name: 'Crisis Combo',
      description: 'Complete 5 urgent tasks in one day',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '🚨',
      color: '#F44336',
      condition: 'urgent_per_day',
      targetValue: 5,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'priority_perfection',
      name: 'Priority Perfection',
      description: 'Complete all urgent tasks in a week',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '✅',
      color: '#4CAF50',
      condition: 'all_urgent_in_week',
      targetValue: 1,
      xpReward: 1500,
    ),
    AchievementModel(
      id: 'priority_master',
      name: 'Priority Master',
      description: 'Complete 25 tasks of each priority',
      category: AchievementCategory.special,
      rarity: AchievementRarity.mythic,
      icon: '👑',
      color: '#FFD700',
      condition: 'priority_master',
      targetValue: 100,
      xpReward: 5000,
    ),

    // TIME-BASED ACHIEVEMENTS (10)
    AchievementModel(
      id: 'time_early_bird',
      name: 'Early Bird',
      description: 'Complete a task before 9 AM',
      category: AchievementCategory.time,
      rarity: AchievementRarity.rare,
      icon: '🌅',
      color: '#FFC107',
      condition: 'early_completion',
      targetValue: 1,
      xpReward: 200,
      hint: 'Start your day right',
    ),
    AchievementModel(
      id: 'time_night_owl',
      name: 'Night Owl',
      description: 'Complete a task after 9 PM',
      category: AchievementCategory.time,
      rarity: AchievementRarity.rare,
      icon: '🦉',
      color: '#3F51B5',
      condition: 'late_completion',
      targetValue: 1,
      xpReward: 150,
    ),
    AchievementModel(
      id: 'time_weekend',
      name: 'Weekend Warrior',
      description: 'Complete 10 tasks on weekends',
      category: AchievementCategory.time,
      rarity: AchievementRarity.rare,
      icon: '📅',
      color: '#9C27B0',
      condition: 'weekend_tasks',
      targetValue: 10,
      xpReward: 300,
    ),
    AchievementModel(
      id: 'time_monday',
      name: 'Monday Motivation',
      description: 'Complete 5 tasks on Mondays',
      category: AchievementCategory.time,
      rarity: AchievementRarity.rare,
      icon: '📅',
      color: '#2196F3',
      condition: 'monday_tasks',
      targetValue: 5,
      xpReward: 200,
    ),
    AchievementModel(
      id: 'time_afternoon',
      name: 'Afternoon Power',
      description: 'Complete 20 tasks between 12-5 PM',
      category: AchievementCategory.time,
      rarity: AchievementRarity.rare,
      icon: '☀️',
      color: '#FF9800',
      condition: 'afternoon_tasks',
      targetValue: 20,
      xpReward: 400,
    ),
    AchievementModel(
      id: 'time_midnight',
      name: 'Midnight Hero',
      description: 'Complete a task at midnight',
      category: AchievementCategory.time,
      rarity: AchievementRarity.epic,
      icon: '🌙',
      color: '#3F51B5',
      condition: 'midnight_completion',
      targetValue: 1,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'time_24hour',
      name: 'Around the Clock',
      description: 'Complete tasks in all 4 time periods',
      category: AchievementCategory.time,
      rarity: AchievementRarity.epic,
      icon: '🕐',
      color: '#FF9800',
      condition: 'all_time_periods',
      targetValue: 4,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'time_consistent',
      name: 'Time Consistency',
      description: 'Complete tasks at the same time for 7 days',
      category: AchievementCategory.time,
      rarity: AchievementRarity.legendary,
      icon: '⏰',
      color: '#4CAF50',
      condition: 'consistent_time',
      targetValue: 7,
      xpReward: 1500,
    ),
    AchievementModel(
      id: 'time_rush_hour',
      name: 'Rush Hour Survivor',
      description: 'Complete 10 tasks during rush hours',
      category: AchievementCategory.time,
      rarity: AchievementRarity.rare,
      icon: '🚦',
      color: '#F44336',
      condition: 'rush_hour_tasks',
      targetValue: 10,
      xpReward: 300,
      hint: '8-10 AM or 5-7 PM',
    ),
    AchievementModel(
      id: 'time_perfection',
      name: 'Time Perfection',
      description: 'Complete a task exactly on time',
      category: AchievementCategory.time,
      rarity: AchievementRarity.legendary,
      icon: '🎯',
      color: '#FFD700',
      condition: 'exact_time',
      targetValue: 1,
      xpReward: 2000,
    ),

    // SPECIAL ACHIEVEMENTS (10)
    AchievementModel(
      id: 'special_perfection',
      name: 'Perfectionist',
      description: 'Complete all tasks in one day',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '💯',
      color: '#FFD700',
      condition: 'perfect_day',
      targetValue: 1,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'special_comeback',
      name: 'Great Comeback',
      description: 'Complete a task after breaking a streak',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🔄',
      color: '#4CAF50',
      condition: 'streak_recovery',
      targetValue: 1,
      xpReward: 300,
    ),
    AchievementModel(
      id: 'special_creator',
      name: 'Task Creator',
      description: 'Create 100 tasks',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '✏️',
      color: '#2196F3',
      condition: 'tasks_created',
      targetValue: 100,
      xpReward: 200,
    ),
    AchievementModel(
      id: 'special_organizer',
      name: 'Organizer',
      description: 'Create 10 different categories',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '📂',
      color: '#9C27B0',
      condition: 'categories_created',
      targetValue: 10,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'special_social',
      name: 'Sharing Success',
      description: 'Share an achievement',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '📢',
      color: '#FF5722',
      condition: 'achievements_shared',
      targetValue: 1,
      xpReward: 100,
    ),
    AchievementModel(
      id: 'special_night_owl_week',
      name: 'Night Owl Week',
      description: 'Complete tasks after 10 PM for a week',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🦉',
      color: '#3F51B5',
      condition: 'late_week_tasks',
      targetValue: 7,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'special_early_riser_week',
      name: 'Early Riser Week',
      description: 'Complete tasks before 8 AM for a week',
      category: AchievementCategory.special,
      rarity: AchievementRarity.epic,
      icon: '🌅',
      color: '#FFC107',
      condition: 'early_week_tasks',
      targetValue: 7,
      xpReward: 1000,
    ),
    AchievementModel(
      id: 'special_marathon',
      name: 'Task Marathon',
      description: 'Complete 100 tasks in one month',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '🏃',
      color: '#4CAF50',
      condition: 'tasks_per_month',
      targetValue: 100,
      xpReward: 2000,
    ),
    AchievementModel(
      id: 'special_speedrun',
      name: 'Speedrun Champion',
      description: 'Complete 50 high-priority tasks in a week',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '⚡',
      color: '#FFC107',
      condition: 'high_priority_week',
      targetValue: 50,
      xpReward: 2500,
    ),
    AchievementModel(
      id: 'special_grand_slam',
      name: 'Grand Slam',
      description: 'Achieve all other special achievements',
      category: AchievementCategory.special,
      rarity: AchievementRarity.mythic,
      icon: '🏆',
      color: '#FFD700',
      condition: 'special_master',
      targetValue: 10,
      xpReward: 10000,
    ),

    // CATEGORY ACHIEVEMENTS (10)
    AchievementModel(
      id: 'cat_work_10',
      name: 'Workhorse',
      description: 'Complete 10 work tasks',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.common,
      icon: '💼',
      color: '#2196F3',
      condition: 'work_tasks',
      targetValue: 10,
      xpReward: 100,
    ),
    AchievementModel(
      id: 'cat_personal_10',
      name: 'Personal Best',
      description: 'Complete 10 personal tasks',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.common,
      icon: '👤',
      color: '#4CAF50',
      condition: 'personal_tasks',
      targetValue: 10,
      xpReward: 100,
    ),
    AchievementModel(
      id: 'cat_health_10',
      name: 'Health Conscious',
      description: 'Complete 10 health tasks',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.common,
      icon: '❤️',
      color: '#F44336',
      condition: 'health_tasks',
      targetValue: 10,
      xpReward: 100,
    ),
    AchievementModel(
      id: 'cat_shopping_10',
      name: 'Shopping Pro',
      description: 'Complete 10 shopping tasks',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.common,
      icon: '🛒',
      color: '#FFC107',
      condition: 'shopping_tasks',
      targetValue: 10,
      xpReward: 100,
    ),
    AchievementModel(
      id: 'cat_education_10',
      name: 'Knowledge Seeker',
      description: 'Complete 10 education tasks',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.common,
      icon: '🎓',
      color: '#9C27B0',
      condition: 'education_tasks',
      targetValue: 10,
      xpReward: 100,
    ),
    AchievementModel(
      id: 'cat_work_50',
      name: 'Professional',
      description: 'Complete 50 work tasks',
      category: AchievementCategory.tasks,
      rarity: AchievementRarity.rare,
      icon: '💼',
      color: '#2196F3',
      condition: 'work_tasks',
      targetValue: 50,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'cat_variety',
      name: 'Category Collector',
      description: 'Complete tasks in 5 different categories',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '🎨',
      color: '#FF5722',
      condition: 'category_variety',
      targetValue: 5,
      xpReward: 500,
    ),
    AchievementModel(
      id: 'cat_master',
      name: 'Category Master',
      description: 'Complete 25 tasks in each category',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '👑',
      color: '#FFD700',
      condition: 'category_master',
      targetValue: 125,
      xpReward: 5000,
    ),
    AchievementModel(
      id: 'cat_custom',
      name: 'Customizer',
      description: 'Create your own category',
      category: AchievementCategory.special,
      rarity: AchievementRarity.rare,
      icon: '✨',
      color: '#9C27B0',
      condition: 'custom_category',
      targetValue: 1,
      xpReward: 200,
      hint: 'Create a task with a new category',
    ),
    AchievementModel(
      id: 'cat_complete',
      name: 'Category Completion',
      description: 'Complete all predefined categories',
      category: AchievementCategory.special,
      rarity: AchievementRarity.legendary,
      icon: '✅',
      color: '#4CAF50',
      condition: 'all_predefined',
      targetValue: 5,
      xpReward: 2000,
    ),
  ];

  // Get achievements by category
  static List<AchievementModel> getByCategory(AchievementCategory category) {
    return all.where((a) => a.category == category).toList();
  }

  // Get achievements by rarity
  static List<AchievementModel> getByRarity(AchievementRarity rarity) {
    return all.where((a) => a.rarity == rarity).toList();
  }

  // Get achievement by ID
  static AchievementModel? getById(String id) {
    try {
      return all.firstWhere((a) => a.id == id);
    } catch (e) {
      return null;
    }
  }

  // Get total count
  static int get totalCount => all.length;
}
